"""Create a double-clickable "Mocap Studio.app" for this checkout (macOS).

The bundle is a thin launcher: it runs desktop/launch.py with this repository's
.venv, so updates to the code take effect without rebuilding. It is built
locally and therefore not quarantined by Gatekeeper.

    python3 scripts/build_macos_app.py            # → dist/Mocap Studio.app
    python3 scripts/build_macos_app.py --install  # also copy to ~/Applications
"""

from __future__ import annotations

import argparse
import plistlib
import shlex
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
APP_NAME = "Mocap Studio"

LAUNCHER = """#!/bin/bash
# Generated by scripts/build_macos_app.py
REPO={repo}
LOG="$HOME/Library/Logs/MocapStudio.log"
mkdir -p "$HOME/Library/Logs"
PY="${{MOCAP_PYTHON:-$REPO/.venv/bin/python}}"
if [ ! -x "$PY" ]; then
  /usr/bin/osascript -e 'display alert "Mocap Studio" message "The Python environment is missing. In Terminal, run:  python3 scripts/manage.py setup"'
  exit 1
fi
cd "$REPO" || exit 1
exec "$PY" -m desktop.launch "$@" >>"$LOG" 2>&1
"""


def make_icon(resources: Path) -> str | None:
    """Draw a simple app icon and convert it with iconutil (if available)."""
    iconutil = shutil.which("iconutil")
    if not iconutil:
        return None
    try:
        import cv2
        import numpy as np
    except ImportError:
        return None
    size = 1024
    img = np.zeros((size, size, 4), np.uint8)
    r, lo, hi = 180, 60, 964  # rounded square, macOS-style margins
    bg = (26, 20, 13, 255)
    cv2.rectangle(img, (lo + r, lo), (hi - r, hi), bg, -1)
    cv2.rectangle(img, (lo, lo + r), (hi, hi - r), bg, -1)
    for cx, cy in [
        (lo + r, lo + r),
        (hi - r, lo + r),
        (lo + r, hi - r),
        (hi - r, hi - r),
    ]:
        cv2.circle(img, (cx, cy), r, bg, -1, cv2.LINE_AA)
    blue = (255, 181, 63, 255)
    orange = (67, 159, 255, 255)
    pts = {
        "head": (512, 250),
        "neck": (512, 350),
        "pelvis": (512, 590),
        "lh": (380, 470),
        "rh": (660, 420),
        "lk": (420, 760),
        "rk": (620, 700),
        "lf": (360, 880),
        "rf": (700, 860),
    }
    cv2.circle(img, pts["head"], 64, (230, 230, 230, 255), -1, cv2.LINE_AA)
    for a, b, c in [
        ("neck", "pelvis", (230, 230, 230, 255)),
        ("neck", "lh", blue),
        ("neck", "rh", orange),
        ("pelvis", "lk", blue),
        ("lk", "lf", blue),
        ("pelvis", "rk", orange),
        ("rk", "rf", orange),
    ]:
        cv2.line(img, pts[a], pts[b], c, 44, cv2.LINE_AA)
    for p in pts.values():
        cv2.circle(img, p, 26, (153, 211, 52, 255), -1, cv2.LINE_AA)
    with tempfile.TemporaryDirectory() as tmp:
        iconset = Path(tmp) / "AppIcon.iconset"
        iconset.mkdir()
        for s in (16, 32, 128, 256, 512):
            for scale in (1, 2):
                px = s * scale
                name = f"icon_{s}x{s}{'@2x' if scale == 2 else ''}.png"
                cv2.imwrite(
                    str(iconset / name),
                    cv2.resize(img, (px, px), interpolation=cv2.INTER_AREA),
                )
        subprocess.run(
            [
                iconutil,
                "-c",
                "icns",
                str(iconset),
                "-o",
                str(resources / "AppIcon.icns"),
            ],
            check=True,
        )
    return "AppIcon"


def build(install: bool = False) -> Path:
    if sys.platform != "darwin":
        print("Note: building a macOS bundle on a non-Mac; the icon is skipped.")
    app = ROOT / "dist" / f"{APP_NAME}.app"
    if app.exists():
        shutil.rmtree(app)
    macos = app / "Contents" / "MacOS"
    resources = app / "Contents" / "Resources"
    macos.mkdir(parents=True)
    resources.mkdir(parents=True)
    exe = macos / "MocapStudio"
    exe.write_text(LAUNCHER.format(repo=shlex.quote(str(ROOT))))
    exe.chmod(0o755)
    icon = make_icon(resources)
    info = {
        "CFBundleName": APP_NAME,
        "CFBundleDisplayName": APP_NAME,
        "CFBundleIdentifier": "local.mocapstudio.live",
        "CFBundleVersion": "1.0.0",
        "CFBundleShortVersionString": "1.0.0",
        "CFBundleExecutable": "MocapStudio",
        "CFBundlePackageType": "APPL",
        "LSMinimumSystemVersion": "12.0",
        "NSHighResolutionCapable": True,
        "LSApplicationCategoryType": "public.app-category.video",
    }
    if icon:
        info["CFBundleIconFile"] = icon
    with (app / "Contents" / "Info.plist").open("wb") as fh:
        plistlib.dump(info, fh)
    print(f"Built {app}")
    if install:
        target = Path.home() / "Applications" / app.name
        target.parent.mkdir(exist_ok=True)
        if target.exists():
            shutil.rmtree(target)
        shutil.copytree(app, target, symlinks=True)
        print(f"Installed {target}")
        return target
    return app


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--install", action="store_true", help="copy to ~/Applications")
    build(p.parse_args().install)
